# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
appName: ${project.name}
version: ${project.version}
domainName: dev.nonprod.oxus.oxuscloud.com
buildNumber: "${env.BUILD_NUMBER}"

nettyWorkerThreads: 2

image:
  repository: docker.dev.nonprod.oxus.oxuscloud.com/${docker.image.prefix}/${project.name}
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

metricsPrometheusEnabled: true
metricsPrometheusStep: PT1M

resources:
  limits:
    cpu: 500m
    memory: 200Mi
  requests:
    cpu: 50m
    memory: 200Mi

nodeSelector: {}

tolerations: []

affinity: {}

