apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}"
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    buildNumber: "{{ .Values.buildNumber }}"
data:
  application.yml: |
    server:
      port: {{ .Values.service.port }}
    spring:
      main:
        banner-mode: off
      zipkin:
        enabled: false
    management:
      endpoints:
        web:
          exposure:
            include: health, prometheus
  logback.xml: |
    <configuration>
      <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
          <encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
              <layout class="oxus.lib.common.logback.OxusLayout">
                  <encode>${logger.encode}</encode>
              </layout>
          </encoder>
      </appender>

      <appender name="ASYNC_CONSOLE" class="ch.qos.logback.classic.AsyncAppender">
          <discardingThreshold>0</discardingThreshold> <!-- default 20, means drop lower event when has 20% capacity remaining -->
          <appender-ref ref="STDOUT"/>
          <queueSize>10000</queueSize> <!-- default 256 -->
          <includeCallerData>false</includeCallerData><!-- default false -->
          <neverBlock>true</neverBlock><!-- default false, set to true to cause the Appender not block the application and just drop the messages -->
      </appender>

      <logger name="oxus.lib" level="info"/>

      <root level="info">
          <appender-ref ref="ASYNC_CONSOLE"/>
      </root>
    </configuration>    
